[package]
name = "zk_auth"
type = "bin"
authors = [""]
compiler_version = ">=0.19.3"

[dependencies]
base64 = { git = "https://github.com/Apocentre/noir-libs", tag = "v0.0.1", directory = "base64" }
collections = { git = "https://github.com/Apocentre/noir-libs", tag = "v0.0.1", directory = "collections" }
